### PR TITLE
Add tax-engine package

### PR DESCRIPTION
**Pull request by dgrunberg**
##### Description
adds package to perform tax-engine calculations

##### Checklist

- [x ] changes don't break existing behavior
- [ ] commit message follows
##### Affected core subsystem(s)

- [ ] web-ui
- [ ] web-services
- [x ] fiat-engine

##### Refers/Fixes
Added new directory tax-engine with tax code and some basic pytests

### CODE REVIEW

**Review by jwaggs — CHANGES_REQUESTED** [review]
Moved the fiat-engine directory into web-services directory, so the branch should rebase off of development and then add the tornado tax package back into the relocated fiat-engine directory. 

Also - as discussed on slack, some files such as main should be renamed since it will not actually be the main file in the cryptocaddy project.

**Comment by dgrunberg** [comment]
I moved tax-engine to be under fiat-engine in it's new location.  Divided code into core and runlocal directories.  Also renamed main.py to control.py.  You can run pytest or runlocal from tax-engine (both work).  The runlocal/runlocal.py does not run due to relative import issues; those can be sorted out later (or delete the file).

**Comment by dgrunberg** [comment]
Also, as a note, I have updated the tax-engine code somewhat (more testing on my own personal situation).  pricing module (under runlocal) does retrieve daily prices from cryptocompare.com (free!) and caches them in a local sqlitedict database.  Since it's under runlocal, it is not needed for the tax computations by themselves.

**Comment by dgrunberg** [comment]
Sorry, not a master at git, so didn't squash my commits into 1.  I think you can do it on the PR (maybe).

**Comment by dgrunberg** [comment]
Changed directory structure to
```
fiat-engine
    └── tornadotax
        ├── doc
        ├── run_local
        ├── tax_engine
        └── tests_local
```

**Review by jwaggs — APPROVED** [review]

**Comment by jwaggs** [comment]
For the sake of forward progress - I've decided to merge this into the code base prior to hooking up the api layer for the tax engine. I'll implement the web specific components to integrate the logic in the near future.

**Pull request merged**
